### ISSUE TITLE
Blocks of consecutive letters should not be contracted.

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-nlb#11]
(untested)

Words that in braille are prefixed with 6-6 should not be contracted.

If this is about a single capital letter, prefix that letter with 56-6.

Not 100% sure what is meant by the last sentence; loosely translated from this in the norwegian contraction spec:

> Når det står 2 ganger pkt. 6 foran et ord, eller pkt. 56 foran en bokstav eller et ord, skal etterfølgende tekst leses som fullskrift, ikke som kortskrift. Gjelder dette én stor bokstav, må det settes |´ pkt. 56-6 foran den.

**Comment by usama49** [comment]
fixed (by preprocessing using CSS text-transform:uncontracted for capital words  )
