### ISSUE TITLE
Work towards a production ready system for NLB

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#18]
by generating the necessary boilerplate text, transcriber notes, table of contents, metadata, etc.

**Comment by bertfrees** [comment]
As I said before I'd like to use the NLB requirements as an example use case for implementing automatic generation of content, and then later use the same approach that you took for the other agencies.

I know some of the requirements, I got some examples from Kari, see: http://snaekobbi.github.io/requirements/generated-content/#4.7:96. But you probably know more details and other requirements.

As you've heard on the call today, all of the agencies' current systems generate content in some way but it's almost always hard-coded. In the new system it would be great to have something more generic and extensible if possible. I'll now give you an overview of what kind of things are already possible, or almost possible, and some other ideas.
- As described in http://snaekobbi.github.io/braille-css-spec/#named-strings CSS supports setting string variables from XML text nodes or attributes. You could use this for example to get the name of the author or the ISBN number from metadata in the header. You can then insert these values at another position in the document using `string()` in combination with `::after` and `::before` pseudo-elements (http://snaekobbi.github.io/braille-css-spec/#the-before-and-after-pseudo-elements).
- As an extension to this, some special string variables could be automatically set by the system so that they can be used with `string()` without the need for an explicit `string-set`. For example, `string(date)` would insert the date.
- The problem with the above method for inserting the date is that a date can be rendered in a lot of different formats, e.g. only the year, or with the month, either in numbers or written out, or with the day of the month, etc. One solution could be to render the `date` variable in a well-known and standard format such as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), and to use the `text-transform` property for processing it (http://snaekobbi.github.io/braille-css-spec/#the-text-transform-property).
- Another solution could be to introduce a new CSS function `date(<date_format>)`, where `<date_format>` would be according to [java.text.SimpleDateFormat](http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) for example. More general-purpose solutions can be thought of too, for example a function called `eval()` which can "evaluate" a programming-language like syntax. More specifically, we could have a function called `-obfl-eval()` which would implement the [OBFL Evaluation Language](http://files.pef-format.org/drafts/obfl/obfl-evaluation-language.html). The OBFL Evaluation Language would have to be extended to support dates.
- Instead of inserting string variables, you can also insert fixed strings with CSS. This is useful if the inserted content does not depend on (metadata in) the source document.
- The above described methods for inserting string content (direct or through variables) are limited to single blocks or inline elements. As soon as more complex and structured content needs to be generated you are out of luck. A possible solution is to support additional kinds of pseudo-elements (`::outside`), sequences of pseudo-elements (`::after(2)`, `::after(3)`, `::before(2)`, `::outside(2)`, etc.) and stacked pseudo-elements (`::after::before`, `::outside::before(2)::before`, etc.), allowing you to build arbitrary structures.
- This approach would work but may result in unreadable CSS. A better idea might be to create the structure in XML and only generate the parts that are not fixed, using CSS. The XML could be included in the main source document with for example the [XInclude](http://www.w3.org/TR/xinclude/) mechanism. If it is not desirable or possible to have `xi:include` elements in the source, we might do something with an option or with a specially invented CSS property. Some thinking will have to be done about which CSS style sheet would have to be applied to the included XML fragment.
- The CSS property `flow` and the function `flow()` can be used to move content to the beginning or end of volumes, either all volumes or specific ones (http://snaekobbi.github.io/braille-css-spec/#named-flows).
- It will soon be possible to create a braille table of contents, optionally in each volume (I'm currently working on this). However this will only work if there is a tables of contents in the source document. In order to support tables of contents also when this is not the case, Davy and I had the idea of automatically generating a table of contents from `h1`, `h2`, etc. elements and to give the resulting `ul` element a well-know class so that it can be selected and further styled with CSS.

**Comment by usama49** [comment]
i tried to these method mentioned above to display Original and Braille Page along with title.
i have couple of issues ,
1: If title is too long, error is generated .
2: Title is displayed on left bottom of the page , but not by using pseudo-elements . I will do more testing.any idea? (css and xml is attached)

[side.xml.txt](https://github.com/snaekobbi/pipeline-mod-nlb/files/56702/side.xml.txt)
[test.css.txt](https://github.com/snaekobbi/pipeline-mod-nlb/files/56703/test.css.txt)
[output-dir.zip.txt](https://github.com/snaekobbi/pipeline-mod-nlb/files/56711/output-dir.zip.txt)

**Comment by bertfrees** [comment]
Thanks for the experimenting. Could you perhaps make two minimal test cases, one each of these issues? That'll make it easier for me to find the problem and debug. If you want I can create a new XProcSpec file where you can add the new tests?

**Comment by bertfrees** [comment]
I'm closing this. If there is anything left you can make new issues.

**Comment by josteinaj** [comment]
Ok.
