### ISSUE TITLE
Remove text-transform: -louis-bold | -louis-ital | ... from XSLT

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#20]
...so that emphasis is not marked up twice (i.e. once through liblouis and once directly by XSLT).

The reason why currently emphasis is not marked up twice is because there is a bug in the Java part that causes `-louis-bold` etc. to be ignored.

Also fix the bug so that we could add an option to choose between XSLT (if order is important) and Liblouis (otherwise) if we would like to.

**Comment by bertfrees** [comment]
Emphasis handling in Liblouis removed, bug not fixed yet.

**Comment by josteinaj** [comment]
@bertfrees is this still an issue? Kari doesn't see anything wrong for bold and emphasis when testing.

**Comment by bertfrees** [comment]
The last part is important I think:

> Also fix the bug so that we could add an option to choose between XSLT (if order is important) and Liblouis (otherwise) if we would like to.

**Comment by josteinaj** [comment]
Ok, but is this a mod-nlb issue then? Or a liblouis/mod-braille issue? If we have it working in XSLT (assuming we do; I haven't tested myself) and there's no performance issue with it then we're fine with that.

**Comment by bertfrees** [comment]
mod-nlb issue

**Comment by bertfrees** [comment]
I'm not promising I can fix this myself, but I'll start by explaining what to do at least. I know you're fine with the XSLT solution so it we could just leave it like that. But in any case the first item (adding a test) is always a good idea.
- [ ] Add JUnit test that shows the problem
- [x] Clean up `NLBTranslator`. Currently the `FromStyledTextToBraille` and `LineBreakingFromStyledText` look very different. This is because I added `LineBreakingFromStyledText` later (see also [NLBTranslator.java#L222](https://github.com/snaekobbi/pipeline-mod-nlb/blob/0d2a3649051684f6e6420c3bbd12ae39a655898c/src/main/java/no/nlb/pipeline/braille/impl/NLBTranslator.java#L222)).
- [ ] Cleaning up / simplifying `NLBTranslator` might already fix the test. But if not, try to fix (in both `FromStyledTextToBraille` and `LineBreakingFromStyledText`).

**Comment by josteinaj** [comment]
Thanks.

I'm removing the snaekobbi label then since we're not depending on this to get a production-ready system.

**Comment by josteinaj** [comment]
Closing this one and replacing it with #57.
