### ISSUE TITLE
Don't break lines after opening quote or before ellipsis or closing quote

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#23]
For example, like this:

```
Lisa gikk langt til
sk…

«Lisa gikk til til gikk
til …»

Dette tror faktisk jeg 
også …

«Nå er det nok forfo i dag,»
sa hun.
```

and not like this:

```
Lisa gikk langt til sk
…

«Lisa gikk til til gikk til
…»

Dette tror faktisk jeg også
…

«Nå er det nok forfo i dag,
» sa hun.
```

**Comment by bertfrees** [comment]
In the cases where there is no space between the letter and the ellipsis or quote it is probably working fine already. In the cases with a space (2nd and 3rd examples) it is probably not working. A possible fix is to replace those spaces with no-break spaces.

@KariRudjord is first going to test some more.

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#5
