### ISSUE TITLE
Clean up tests a bit

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#24]
- [x] test_translator.xprocspec is failing.
- [ ] If possibly remove or replace pending tests, otherwise explain why it is pending.
- [ ] test_css_formatter.xprocspec isn't really testing anything from this module. Better would be to turn this into a script test, or move it to pipeline-mod-braille.
- [ ] The expected result of some tests hasn't been verified.
- [ ] The default CSS could use some more tests.
- [ ] test_script.xprocspec should be remove because now we have test_dtbook-to-pef.xprocspec etc.
- [ ] test_dtbook-to-pef.xprocspec should ideally not contain any embedded CSS, it should use as much as possible the default CSS and options.
- [ ] use `x:pef-compare` from http://www.daisy.org/pipeline/modules/braille/pef-utils/library.xpl because more robust.

**Comment by josteinaj** [comment]
I agree. I'll have a look at it.

**Comment by josteinaj** [comment]
CC @usama49

**Comment by bertfrees** [comment]
Updated list of things to do.

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#6
