### ISSUE TITLE
Should 5-2 be used surrounding text in other languages when using the norwegian standard?

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-nlb#25]
In the norwegian braille standard, it says:

> Tekst på fremmed språk med vedkommende språks punktskriftstandard (5-2 foran og etter)

In english: Text in a foreign language using that languages braille standard (5-2 before and after)

We now use 5-2 before and after foreign language text, but we use the norwegian braille standard (norwegian liblouis table / character mapping).

@KariRudjord should we drop the 5-2 before and after when we're using the norwegian braille table to render foreign languages? We can enable it in the future if we add support for using foreign braille standards.

**Comment by KariRudjord** [comment]
Yes!

**Comment by josteinaj** [comment]
Ok. So @usama49 since you're working on the pre-processing now, maybe you could remove the stuff that adds 5-2 before and after foreign languages? Just commenting out `<xsl:value-of select="$uncontracted-pre"/>` and `<xsl:value-of select="$uncontracted-post"/>` in `pre-processing.xsl` should work. It means we won't do anything in that XSLT for now so you could alternatively comment out the `<p:xslt>` from `pre-processing.xpl`.

**Comment by josteinaj** [comment]
@usama49 ...also it will affect the tests I guess, so you would need to remove the 5-2 dots in the `x:expect` elements in `test_dtbook-to-pef.xprocspec` as well (I moved the xml:lang tests there, they were in `test_transform.xprocspec` earlier).

**Comment by usama49** [comment]
ok. i will do it and Edit tests

**Comment by josteinaj** [comment]
fixed in cddf441771426a770d49d1b1a9e5243d95ef628d
