### ISSUE TITLE
Decide what to do when contracting norwegian text inside foreign text

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-nlb#26]
For instance:

``` xml
<div xml:lang="no">
    <p>Dette er et utdrag fra en engelsk bok om norge:</p>
    <blockquote xml:lang="en">
        <p>Norwegian is not english.
           In norwegian you say "<span xml:lang="no">God morgen!</span>"
           instead of "Good morning!".</p>
    </blockquote>
</div>
```

@KariRudjord In this example, the first paragraph should be contracted, and the english text should not be contracted. But what about the "God morgen!" text inside the english text?

(Currently we do not contract norwegian text that is found inside foreign language text.)

**Comment by KariRudjord** [comment]
I think, if the norwegian text is inside the foreign language text, who is not contracted, the norwegian text should be written the same - uncontracted.

**Comment by josteinaj** [comment]
Ok, great. That's what we do now so then I'll close this issue.
