### ISSUE TITLE
Make text alternating on odd and even pages when line-spacing is "double"

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#31]
Kari has used the following CSS to successfully use this feature in her system test:

``` css
@page:left {
  margin-top: 1;
}
```

However it seems it was never added to the NLB's default style sheet. If you add it make sure to wrap it in a conditional, because the offset may only be there for double line spacing:

``` css
@if $line-spacing == double {
  ...
}
```

**Comment by usama49** [comment]
Added in CSS
