### ISSUE TITLE
Automatic numbering of notes

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#33]
If a book has notes marked with \* and the notes are collected in end of volume, numbering of notes is necessary to recognize them.

**Comment by bertfrees** [comment]
@KariRudjord does this numbering need to be reset to 1 for each volume?

**Comment by KariRudjord** [comment]
No, it doesn't need that.

**Comment by bertfrees** [comment]
OK. In that case it should be fairly simple to implement. The only catch is that if we want to have the fallback behavior (i.e. first try to flow notes at the bottom of the page, if that fails flow to the end of the volume) the notes will look the same regardless of where they are rendered: that means that if you want them to be numbered if at the back of the volume, they will also be numbered if at the bottom of the page.

**Comment by usama49** [comment]
fixed
