### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#34]
Have we determined yet what we want to do with tables? It can be useful to look at what other have done:
- [SBS](https://github.com/snaekobbi/pipeline-mod-sbs/blob/5694ef84eb57d7c80d9af7fac5dbe3eaa31a11af/src/main/resources/css/default.scss#L283)
- [Celia](https://github.com/snaekobbi/pipeline-mod-celia/blob/1bf7946245500bb577c9eff351755e12c735ce96/src/main/resources/css/celia-default.scss#L199)
- [Nota](https://github.com/snaekobbi/pipeline-mod-nota/blob/e5258f187ac0a1f348847a9bea427402e5b91111/src/main/resources/css/default.scss#L145)
- [Dedicon](https://github.com/snaekobbi/pipeline-mod-dedicon/blob/fa38597ece4d46c1c62440fd46b705a65f3cc35f/src/main/resources/css/dedicon-default.scss#L280)

**Comment by josteinaj** [comment]
@usama49 will you have a look and talk to @KariRudjord if needed?

**Comment by josteinaj** [comment]
Let's test how this works now (since I think we have tables as lists already?), and if needed we can create more specific issues for how to improve the tables later.

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#8
