### ISSUE TITLE
EPUB3/HTML support

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#35]
There is already a epub3-to-pef script but no NLB-specific CSS file for it yet.

To do:
- [x] Port CSS for DTBook to EPUB
- [x] Tests for epub3-to-pef

**Comment by josteinaj** [comment]
We might even consider using the same CSS file for all formats since the CSS will be very similar across formats.

**Comment by bertfrees** [comment]
Should I assign this to you @usama49?

**Comment by usama49** [comment]
it's ok. i will make new CSS for EPUB

**Comment by bertfrees** [comment]
@usama49: So what is the status here? You told me the CSS is done but were not sure the framework could handle EPUB as input. Did you do some unit tests? I'd like to make sure it somewhat works before I merge and move this to system testing.

**Comment by usama49** [comment]
Hi @bertfrees 
we have tested EPUB and framework  is accepting Epub. se pull request #39. we have to doable e-pub boiler plate due to error 

```
[INFO] Coding error: unexpected /css:_/css:_[1] (mode was sequence)
[ERROR] Processing terminated by xsl:message at line 1388 in css-to-obfl.xsl
```

when you have time please look at it.
Thanks

**Comment by bertfrees** [comment]
Fixed the bug, see https://github.com/daisy/pipeline-mod-braille/commit/d8283d280a6b3fcba9c5f874ef2089354b9a7755.

**Comment by bertfrees** [comment]
After testing by Kari some more optimizations are required. Ammar is working on it.

**Comment by josteinaj** [comment]
EPUB3/HTML is supported. More work needed in the future but we have initial support for it.
