### ISSUE TITLE
Some fixes to norwegian table (sami reverse circumlex, sami vs norse acute, dashes)

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-nlb#36]
- Sami reverse circumflex gets universal accent, but should've had (156)
- a with acute should be Sami á (12356). Now it is norse á (16).
- Long and short dash becomes "equals". Short dash should be (36) and long dash should be (36-36).

@usama49 can we assign this issue to you?

**Comment by usama49** [comment]
it's ok

**Comment by usama49** [comment]
@KariRudjord i have fixed Sami á and dashes. can you explain (Sami reverse circumflex) character.

**Comment by usama49** [comment]
fixed

**Comment by bertfrees** [comment]
@usama49: Kari says "a acute" is fixed, but "sami reverse circumflex" and "dashes" are still broken. Will you have another look?

**Comment by usama49** [comment]
I will look again.

**Comment by KariRudjord** [comment]
@usama49 I have retested, and it seems that dashes are working! (I should have seen it earlier, I had to improve my testmaterial). Only sami s/S with reverse circumflex (caron) is not working yet. Should be 156

**Comment by usama49** [comment]
@KariRudjord I have changed table. Now dashes and reverse circumflex should work after Bert will deploy new version.
