### ISSUE TITLE
Either implement or hide unimplemented options

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#42]
Kari thinks some options would be useful to have:
- Colophon: choice between front or back
- Skip processing of notes

Other unimplemented options should be hidden in the user interface.

**Comment by KariRudjord** [comment]
To create very small volumes don't work. I tried with 17 pages per volume. (job #5092-#5093). First, the option to adjust in GUI don't work, but Jostein found an error in NLB-script, so it should work after next release. But when I add a CSS, it is possible to divide in volumes of about 35 pages. When I try with 17, it is not possible anymore. I don't get "Failed", but the process is running and running. Is there a lower limit here or is it an error that can be fixed? @bertfrees @ammar @josteinaj

**Comment by bertfrees** [comment]
Job 5093 did finish. I'm looking at the logs now. This could be a bug in Dotify. Will investigate some more.

**Comment by bertfrees** [comment]
Job 5092 also finished.

**Comment by bertfrees** [comment]
> Colophon: choice between front or back

is that done?

**Comment by josteinaj** [comment]
No but it's tracked here: #48
