### ISSUE TITLE
Share non-standard hyphenation patterns with LibreOffice?

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#44]
I was at a talk at FOSDEM were they explicitly asked for contributions to the Norwegian dictionaries (see https://fosdem.org/2016/schedule/event/wysiwyg/attachments/slides/1201/export/events/attachments/wysiwyg/slides/1201/future3.pdf, page 2). So that means that there is already support for non-standard hyphenation in LibreOffice but needs to be improved. I'm not sure if they would be interested in your long list of words, maybe they expect something more rule-based. But it's worth asking, and if they don't want it then at least we know what to do if we want to collaborate with them.

**Comment by josteinaj** [comment]
Interesting, thanks! I'll wait with contacting them though until I have more time (i.e. after the Take Part conference etc.).

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#10
