### ISSUE TITLE
Space in numbers

### ISSUE THREAD

**Issue by KariRudjord** [snaekobbi/pipeline-mod-nlb#47]
E.g. 10 000, telephone 22 08 34 57 or 3095 05 55555. Is it possible to make a rule so that space between digits is removed? (To avoid new number sign in the middel of the number or splitting in two rows when in end of a row)  

@bertfrees @josteinaj

**Comment by josteinaj** [comment]
We can remove spaces between numbers during preprocessing by using a regex. @bertfrees is it easier and/or more efficient to do it somewhere other then during preprocessing?

**Comment by bertfrees** [comment]
I don't know about more efficient. But it could also be done in Liblouis I guess. And the more you can move to Liblouis the more useful it'll become outside the Pipeline.

**Comment by josteinaj** [comment]
Ok. I don't know (or have time to get to know) how to do that in liblouis.

@egli: would SBS be interested in solving this issue in liblouis? Otherwise we'll do it in our preprocessing XSLT.

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#12
