### ISSUE TITLE
Put compiled hyphenation dictionary under source control

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-nlb#49]
As suggested here: https://github.com/snaekobbi/pipeline-mod-nlb/commit/ed0275a686f7369f84387741522518451e3ac7dc#commitcomment-17669751

**Comment by josteinaj** [comment]
fixed by @bertfrees

**Comment by bertfrees** [comment]
I did a very quick fix in order to be able to release easier. I just uncommented the whole section to generate the table, is that alright? Probably better to have a special Maven/Ant/Make target to regenerate the table.

**Comment by josteinaj** [comment]
Oh, ok. So if we want to recompile we just uncomment? A special target would of course be better yes, but for now this is fine I think.
