### ISSUE TITLE
First half of word is deleted when non-standard hyphenation break point is at page width

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-nlb#51]
To illustrate, these three lines represent the page width, box/paragraph width, and braille text (shown as characters). As I see them in the PEF:

```
|----------------------------|            (page width 30)
  |------------------------|              (26 cells left after 2 padding left/right)
  VOLLEYBALLEDEREN VOLLEYBALLEDEREN
```

In this case, the paragraph box ends between `VOLLEYBAL` and `LEDEREN`, which is also the hyphenation point for the word `VOLLEYBALLEDEREN`. Hyphenated, the word should be `VOLLEYBALL-LEDEREN`

I tested with a standard hyphenation word as well (SAMMFUNNSFORSKERE) to see if the same problem occurs there when the hyphenation point coincides with the box width, but it does not. So I think the problem here is that for non-standard hyphenation, an extra character is inserted, making that part of the word too long to fit, and as a result that part of the word is deleted. The result after hyphenation from the previous example is:

```
|----------------------------|
  |------------------------|
  VOLLEYBALLEDEREN LEDEREN
```

**Comment by bertfrees** [comment]
Oops, that's a bug alright!

**Comment by bertfrees** [comment]
You were going to provide a test in mod-nlb right?

**Comment by josteinaj** [comment]
Oh, right, yeah I can do that. Thanks for reminding me.

**Comment by josteinaj** [comment]
@bertfrees test added to branch `issue-51`.

**Comment by josteinaj** [comment]
@usama49: this needs to be high on our list for testing.

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#14
