### ISSUE TITLE
Replace release notes on Github with links to NEWS file

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#54]
to solve problem of duplication described at http://www.mehdi-khalili.com/better-git-release-notes. I've already done this for the pipeline-mod-braille repository but the same can be done for pipeline-mod-nlb, pipeline-mod-celia, pipeline-mod-dedicon, pipeline-mod-mtm, pipeline-mod-sbs, pipeline-mod-nota and snaekobbi/system.

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#16
