### ISSUE TITLE
Default character for unrecognized characters

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-nlb#6]
When liblouis encounters an unrecognized character, it seems to generate a long braille pattern based maybe on the unicode value. This can be quite confusing for the end-user, and it would probably be better to have a default character for these cases. It could for instance default to a question mark, a space character, or something else.

@bertfrees is this possible with an opcode or should it be part of preprocessing?

**Comment by bertfrees** [comment]
This is already supported in liblouis. See [Miscellaneous Opcodes](http://liblouis.org/documentation/liblouis.html#Miscellaneous-Opcodes):

> **undefined dots**
> 
> If this opcode is used in a table any characters which have not been defined in the table but are encountered in the text will be replaced by the dot pattern. If this opcode is not used, any undefined characters are replaced by '\xhhhh', where the h’s are hexadecimal digits. 

Another possibility is to return an error or alert the user when encountering undefined input characters (https://github.com/snaekobbi/liblouis/issues/11, https://github.com/snaekobbi/pipeline-mod-braille/issues/54).

**Comment by josteinaj** [comment]
Interesting, thanks! We'll try adding that opcode to the norwegian table then.

**Comment by usama49** [comment]
fixed. undefined character are treated as "?" sign. I have up dated table.
