### ISSUE TITLE
Full support for combining marks

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-nlb#7]
Many of the diacritic letters can also be written by using combining marks:
http://unicode-table.com/en/search/?q=combining

For instance: "å" (U+61 U+030A) and "å" (U+E5).

Many diacritic letters, such as e̊, can only be written by using these combining marks.

We could generate a table (or extend the existing one) for these diacritics where we include all combinations of the letters a-z with all the combining marks (or at least the relevant combining marks). At most, this means 12896 new definitions, but we could drop most of the rules if that makes it inefficient.

Alternatively, we could do some preprocessing to replace the trailing combining marks with dot 4 before the character.

In any case, these marks seem to be rare so this is not a high priority.

**Comment by bertfrees** [comment]
Related: https://github.com/liblouis/liblouis/issues/98

**Comment by josteinaj** [comment]
Opcodes such as `lowercase` and `sign` does not work with combining characters since they are not recognized as a single character.

**Comment by josteinaj** [comment]
Will wait until liblouis has native support for combining marks.

**Comment by josteinaj** [comment]
See also: #59

**Comment by josteinaj** [comment]
This issue was moved to nlbdev/pipeline#4
